Senity-Waved/Waved_BE

- build.gradle
- src/main/java/com/senity/waved/base/redis/Redis.java
- src/main/java/com/senity/waved/base/redis/RedisProperties.java
- src/main/java/com/senity/waved/base/redis/RedisRepository.java
- src/main/java/com/senity/waved/base/redis/RedisUtil.java
- src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
- src/main/resources/application.yml
> Feat: 로그인 Redis 적용

- src/main/java/com/senity/waved/base/globalExceptionHandler/GlobalExceptionHandler.java
- src/main/java/com/senity/waved/base/redis/Redis.java
- src/main/java/com/senity/waved/base/redis/RedisRepository.java
- src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
- src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
- src/main/java/com/senity/waved/domain/member/controller/MemberController.java
- src/main/java/com/senity/waved/domain/member/dto/MemberJoinDto.java
- src/main/java/com/senity/waved/domain/member/entity/Gender.java
- src/main/java/com/senity/waved/domain/member/entity/Member.java
- src/main/java/com/senity/waved/domain/member/repository/MemberRepository.java
- src/main/java/com/senity/waved/domain/member/service/MemberService.java
- src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
> Feat: 회원가입 커스터마이징 기능 구현

- src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
- src/main/java/com/senity/waved/domain/Challenge/controller/ChallengeController.java
- src/main/java/com/senity/waved/domain/Challenge/entity/Challenge.java
- src/main/java/com/senity/waved/domain/Challenge/repository/ChallengeRepository.java
- src/main/java/com/senity/waved/domain/Challenge/service/ChallengeService.java
- src/main/java/com/senity/waved/domain/Challenge/service/ChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/ChanllengeGroup/controller/ChallengeGroupController.java
- src/main/java/com/senity/waved/domain/ChanllengeGroup/entity/ChallengeGroup.java
- src/main/java/com/senity/waved/domain/ChanllengeGroup/repository/ChallengeGroupRepository.java
- src/main/java/com/senity/waved/domain/ChanllengeGroup/service/ChallengeGroupService.java
- src/main/java/com/senity/waved/domain/ChanllengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/member/entity/Member.java
- src/main/java/com/senity/waved/domain/myChallenge/controller/myChanllengeController.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/Status.java
- src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeService.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
> Chore: 챌린지 관련 패키지 구조 추가

- src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
- src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
- src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
- src/main/java/com/senity/waved/domain/challengeGroup/exception/ChallengeGroupNotFoundException.java
- src/main/java/com/senity/waved/domain/member/entity/Member.java
- src/main/java/com/senity/waved/domain/member/repository/MemberRepository.java
- src/main/java/com/senity/waved/domain/quiz/dto/response/QuizResponseDto.java
- src/main/java/com/senity/waved/domain/quiz/entity/Quiz.java
- src/main/java/com/senity/waved/domain/quiz/exception/QuizNotFoundException.java
- src/main/java/com/senity/waved/domain/quiz/repository/QuizRepository.java
- src/main/java/com/senity/waved/domain/quiz/service/QuizService.java
- src/main/java/com/senity/waved/domain/quiz/service/QuizServiceImpl.java
- src/main/java/com/senity/waved/domain/verification/controller/VerificationController.java
- src/main/java/com/senity/waved/domain/verification/dto/request/VerificationRequestDto.java
- src/main/java/com/senity/waved/domain/verification/entity/Verification.java
- src/main/java/com/senity/waved/domain/verification/exception/ChallengeGroupVerificationException.java
- src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
- src/main/java/com/senity/waved/domain/verification/service/GithubApi.java
- src/main/java/com/senity/waved/domain/verification/service/GithubService.java
- src/main/java/com/senity/waved/domain/verification/service/VerificationService.java
- src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
> ex) #13 
>
>
> 사진, 글, 깃헙 인증 방식 기능 구현했습니다. 인증 중복 처리는 다음 이슈에서 진행하겠습니다.
> Feat: 챌린지 인증방식 기능 구현

- src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
- src/main/java/com/senity/waved/common/BaseEntity.java
- src/main/java/com/senity/waved/domain/challenge/controller/ChallengeController.java
- src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
- src/main/java/com/senity/waved/domain/challenge/repository/ChallengeRepository.java
- src/main/java/com/senity/waved/domain/challenge/service/ChallengeService.java
- src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
- src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
- src/main/java/com/senity/waved/domain/member/controller/MemberController.java
- src/main/java/com/senity/waved/domain/member/entity/Member.java
- src/main/java/com/senity/waved/domain/member/service/MemberService.java
- src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
- src/main/java/com/senity/waved/domain/myChallenge/controller/MyChallengeController.java
- src/main/java/com/senity/waved/domain/myChallenge/controller/myChanllengeController.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/Status.java
- src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeService.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/review/controller/ReviewController.java
- src/main/java/com/senity/waved/domain/review/dto/response/ReviewResponseDto.java
- src/main/java/com/senity/waved/domain/review/entity/Review.java
- src/main/java/com/senity/waved/domain/review/repository/ReviewRepository.java
- src/main/java/com/senity/waved/domain/review/service/ReviewService.java
- src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
- src/main/java/com/senity/waved/domain/verification/entity/Verification.java
> Feature: 챌린지 리뷰 기능 추가 및 엔티티 수정

- src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
- src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
- src/main/java/com/senity/waved/domain/member/entity/Member.java
> Fix: 생성자 초기화 되도록 수정

- src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
- src/main/java/com/senity/waved/domain/challengeGroup/dto/response/VerificationListResponseDto.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/member/entity/Member.java
- src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
- src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
- src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
> ex) #24 
>
> 인증 내역 조회(마이챌린지)에서 성공(2), 실패(1), 제출안함(0)으로 되도록! 
챌린지 그룹의 날짜별 인증 내역 조회 타입 변경
깃헙 연동 여부 확인 및 업데이트 로직 추가
> Feat: 깃허브 연동 여부 확인 및 인증 업데이트 기능 구현

- src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/verification/exception/AlreadyVerifiedException.java
- src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
> ex) #16 
>
>
> 챌린지 인증 방식 중복 불가능 하도록 리팩토링 -> 추후 깃헙 수정 기능 추가한다면 수정해야 할 것 같습니다.
당일 인증 여부 체크 로직 구현
> Refactor: 챌린지 인증 방식 중복 불가능 하도록 리팩토링

- .github/workflows/main_waved.yml
- src/main/java/com/senity/waved/base/config/WebSecurityConfig.java
- src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
- src/main/java/com/senity/waved/domain/member/controller/MemberController.java
- src/main/resources/application.yml
- src/main/resources/log4jdbc.log4j2.properties
> Fix: Front token 전달 형식 변경 및 데이터베이스 자동 종료 문제 해결

- src/main/java/com/senity/waved/domain/challengeGroup/dto/response/VerificationListResponseDto.java
> Fix: 인증 내역 조회에서 nickname 필드 반환하도록 수정

- src/main/java/com/senity/waved/base/jwt/JwtFilter.java
- src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
- src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
- src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
- src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
- src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
- src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
- src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
> ex) #49 
>
>  환급 여부/달성 여부 
> 리뷰 서비스 예외 처리
> Refactor: 챌린지 환급 여부/달성 여부 반환 및 리뷰 서비스 예외 처리

- build.gradle
- src/main/java/com/senity/waved/base/config/IamportClientConfig.java
- src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
- src/main/resources/application.yml
> Refcator: 결제 검증 API 예치금 리팩토링

- build.gradle
- src/main/java/com/senity/waved/base/config/IamportClientConfig.java
- src/main/resources/application.yml
> Fix: iamport 연동

- src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyVerifsResponseDto.java
- src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/quiz/repository/QuizRepository.java
- src/main/java/com/senity/waved/domain/quiz/service/QuizService.java
- src/main/java/com/senity/waved/domain/quiz/service/QuizServiceImpl.java
- src/main/java/com/senity/waved/domain/verification/controller/VerificationController.java
- src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
> Feat: 내 인증 내역 조회 & 날짜별 기술 면접 문제 조회 API

- src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
- src/main/java/com/senity/waved/domain/paymentRecord/dto/response/PaymentRecordResponseDto.java
- src/main/java/com/senity/waved/domain/paymentRecord/entity/PaymentRecord.java
- src/main/java/com/senity/waved/domain/paymentRecord/repository/PaymentRecordRepository.java
- src/main/java/com/senity/waved/domain/review/repository/ReviewRepository.java
> Feat: 페이지네이션 적용 및 최신순 정렬

- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeCompletedDto.java
- src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeProgressDto.java
- src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
- src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
- src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
- src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
> Refactor: 필요없는 Null 값 정리 및 신청 후 결제 여부 확인하는 필드 추가

- src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
- src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
> Fix: 무료 챌린지 재신청 가능하도록 수정

- src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
- src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
- src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
- src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
- src/main/java/com/senity/waved/domain/notification/controller/NotificationController.java
- src/main/java/com/senity/waved/domain/notification/dto/response/NotificationResponseDto.java
- src/main/java/com/senity/waved/domain/notification/entity/Notification.java
- src/main/java/com/senity/waved/domain/notification/repository/NotificationRepository.java
- src/main/java/com/senity/waved/domain/notification/service/NotificationService.java
- src/main/java/com/senity/waved/domain/notification/service/NotificationServiceImpl.java
- src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
> ex) #이슈번호, #이슈번호
>
>  챌린지 그룹 생성 자동화
> 알림 도메인 추가 
>
> Feat: 챌린지 그룹 생성 스케줄링 및 알림 도메인 추가

- src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
- src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
- src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/event/controller/EventController.java
- src/main/java/com/senity/waved/domain/notification/controller/NotificationController.java
- src/main/java/com/senity/waved/domain/notification/repository/NotificationRepository.java
- src/main/java/com/senity/waved/domain/notification/service/NotificationService.java
- src/main/java/com/senity/waved/domain/notification/service/NotificationServiceImpl.java
- src/main/java/com/senity/waved/domain/verification/exception/AlreadyDeletedVerificationException.java
- src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
> #79
> 알림 일주일 후 자동 삭제 로직 추가
> 관리자 인증 내역 조회 시 탈퇴한 멤버 오류 발생 문제 해결
> .
>
> Feat: 알림 삭제 로직 추가 및 관리자 탈퇴 서버 관련 문제 해결

- src/main/java/com/senity/waved/base/jwt/TokenProvider.java
- src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
- src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
- src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupHomeResponseDto.java
- src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
- src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
- src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
> ex) #83
> 챌린지 imageUrl 전달 방식 변경
>  참여자수 변경 로직 수정 
> .
> Fix: 참여자수 변경 로직 수정 및 imageUrl 전달 방식 변경
